//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 12:49:43 AM EET 
//


package fb2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stylesheet" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="description"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="title-info" type="{http://www.gribuser.ru/xml/fictionbook/2.0}title-infoType"/&gt;
 *                   &lt;element name="src-title-info" type="{http://www.gribuser.ru/xml/fictionbook/2.0}title-infoType" minOccurs="0"/&gt;
 *                   &lt;element name="document-info"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded"/&gt;
 *                             &lt;element name="program-used" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
 *                             &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType"/&gt;
 *                             &lt;element name="src-url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                             &lt;element name="src-ocr" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *                             &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                             &lt;element name="history" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/&gt;
 *                             &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="publish-info" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="book-name" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
 *                             &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
 *                             &lt;element name="city" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
 *                             &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/&gt;
 *                             &lt;element name="isbn" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
 *                             &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="custom-info" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0&gt;textFieldType"&gt;
 *                           &lt;attribute name="info-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="output" type="{http://www.gribuser.ru/xml/fictionbook/2.0}shareInstructionType" maxOccurs="2" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="body" type="{http://www.gribuser.ru/xml/fictionbook/2.0}bodyType"/&gt;
 *         &lt;element name="binary" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;base64Binary"&gt;
 *                 &lt;attribute name="content-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stylesheet",
    "description",
    "body",
    "binary"
})
@XmlRootElement(name = "FictionBook")
public class FictionBook {

    protected List<FictionBook.Stylesheet> stylesheet;
    @XmlElement(required = true)
    protected FictionBook.Description description;
    @XmlElement(required = true)
    protected BodyType body;
    protected List<FictionBook.Binary> binary;

    /**
     * Gets the value of the stylesheet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stylesheet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStylesheet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FictionBook.Stylesheet }
     * 
     * 
     */
    public List<FictionBook.Stylesheet> getStylesheet() {
        if (stylesheet == null) {
            stylesheet = new ArrayList<FictionBook.Stylesheet>();
        }
        return this.stylesheet;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FictionBook.Description }
     *     
     */
    public FictionBook.Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FictionBook.Description }
     *     
     */
    public void setDescription(FictionBook.Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link BodyType }
     *     
     */
    public BodyType getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyType }
     *     
     */
    public void setBody(BodyType value) {
        this.body = value;
    }

    /**
     * Gets the value of the binary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FictionBook.Binary }
     * 
     * 
     */
    public List<FictionBook.Binary> getBinary() {
        if (binary == null) {
            binary = new ArrayList<FictionBook.Binary>();
        }
        return this.binary;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;base64Binary"&gt;
     *       &lt;attribute name="content-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Binary {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "content-type", required = true)
        protected String contentType;
        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets the value of the contentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentType() {
            return contentType;
        }

        /**
         * Sets the value of the contentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentType(String value) {
            this.contentType = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="title-info" type="{http://www.gribuser.ru/xml/fictionbook/2.0}title-infoType"/&gt;
     *         &lt;element name="src-title-info" type="{http://www.gribuser.ru/xml/fictionbook/2.0}title-infoType" minOccurs="0"/&gt;
     *         &lt;element name="document-info"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded"/&gt;
     *                   &lt;element name="program-used" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
     *                   &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType"/&gt;
     *                   &lt;element name="src-url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                   &lt;element name="src-ocr" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
     *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *                   &lt;element name="history" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/&gt;
     *                   &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="publish-info" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="book-name" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
     *                   &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
     *                   &lt;element name="city" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
     *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/&gt;
     *                   &lt;element name="isbn" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
     *                   &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="custom-info" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0&gt;textFieldType"&gt;
     *                 &lt;attribute name="info-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="output" type="{http://www.gribuser.ru/xml/fictionbook/2.0}shareInstructionType" maxOccurs="2" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titleInfo",
        "srcTitleInfo",
        "documentInfo",
        "publishInfo",
        "customInfo",
        "output"
    })
    public static class Description {

        @XmlElement(name = "title-info", required = true)
        protected TitleInfoType titleInfo;
        @XmlElement(name = "src-title-info")
        protected TitleInfoType srcTitleInfo;
        @XmlElement(name = "document-info", required = true)
        protected FictionBook.Description.DocumentInfo documentInfo;
        @XmlElement(name = "publish-info")
        protected FictionBook.Description.PublishInfo publishInfo;
        @XmlElement(name = "custom-info")
        protected List<FictionBook.Description.CustomInfo> customInfo;
        protected List<ShareInstructionType> output;

        /**
         * Gets the value of the titleInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TitleInfoType }
         *     
         */
        public TitleInfoType getTitleInfo() {
            return titleInfo;
        }

        /**
         * Sets the value of the titleInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TitleInfoType }
         *     
         */
        public void setTitleInfo(TitleInfoType value) {
            this.titleInfo = value;
        }

        /**
         * Gets the value of the srcTitleInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TitleInfoType }
         *     
         */
        public TitleInfoType getSrcTitleInfo() {
            return srcTitleInfo;
        }

        /**
         * Sets the value of the srcTitleInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TitleInfoType }
         *     
         */
        public void setSrcTitleInfo(TitleInfoType value) {
            this.srcTitleInfo = value;
        }

        /**
         * Gets the value of the documentInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FictionBook.Description.DocumentInfo }
         *     
         */
        public FictionBook.Description.DocumentInfo getDocumentInfo() {
            return documentInfo;
        }

        /**
         * Sets the value of the documentInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FictionBook.Description.DocumentInfo }
         *     
         */
        public void setDocumentInfo(FictionBook.Description.DocumentInfo value) {
            this.documentInfo = value;
        }

        /**
         * Gets the value of the publishInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FictionBook.Description.PublishInfo }
         *     
         */
        public FictionBook.Description.PublishInfo getPublishInfo() {
            return publishInfo;
        }

        /**
         * Sets the value of the publishInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FictionBook.Description.PublishInfo }
         *     
         */
        public void setPublishInfo(FictionBook.Description.PublishInfo value) {
            this.publishInfo = value;
        }

        /**
         * Gets the value of the customInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FictionBook.Description.CustomInfo }
         * 
         * 
         */
        public List<FictionBook.Description.CustomInfo> getCustomInfo() {
            if (customInfo == null) {
                customInfo = new ArrayList<FictionBook.Description.CustomInfo>();
            }
            return this.customInfo;
        }

        /**
         * Gets the value of the output property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the output property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOutput().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ShareInstructionType }
         * 
         * 
         */
        public List<ShareInstructionType> getOutput() {
            if (output == null) {
                output = new ArrayList<ShareInstructionType>();
            }
            return this.output;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0&gt;textFieldType"&gt;
         *       &lt;attribute name="info-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CustomInfo
            extends TextFieldType
        {

            @XmlAttribute(name = "info-type", required = true)
            protected String infoType;

            /**
             * Gets the value of the infoType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInfoType() {
                return infoType;
            }

            /**
             * Sets the value of the infoType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInfoType(String value) {
                this.infoType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded"/&gt;
         *         &lt;element name="program-used" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
         *         &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType"/&gt;
         *         &lt;element name="src-url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
         *         &lt;element name="src-ocr" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
         *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
         *         &lt;element name="history" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/&gt;
         *         &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "author",
            "programUsed",
            "date",
            "srcUrl",
            "srcOcr",
            "id",
            "version",
            "history",
            "publisher"
        })
        public static class DocumentInfo {

            @XmlElement(required = true)
            protected List<AuthorType> author;
            @XmlElement(name = "program-used")
            protected TextFieldType programUsed;
            @XmlElement(required = true)
            protected DateType date;
            @XmlElement(name = "src-url")
            protected List<String> srcUrl;
            @XmlElement(name = "src-ocr")
            protected TextFieldType srcOcr;
            @XmlElement(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String id;
            protected float version;
            protected AnnotationType history;
            protected List<AuthorType> publisher;

            /**
             * Gets the value of the author property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the author property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAuthor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AuthorType }
             * 
             * 
             */
            public List<AuthorType> getAuthor() {
                if (author == null) {
                    author = new ArrayList<AuthorType>();
                }
                return this.author;
            }

            /**
             * Gets the value of the programUsed property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getProgramUsed() {
                return programUsed;
            }

            /**
             * Sets the value of the programUsed property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setProgramUsed(TextFieldType value) {
                this.programUsed = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link DateType }
             *     
             */
            public DateType getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link DateType }
             *     
             */
            public void setDate(DateType value) {
                this.date = value;
            }

            /**
             * Gets the value of the srcUrl property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the srcUrl property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSrcUrl().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getSrcUrl() {
                if (srcUrl == null) {
                    srcUrl = new ArrayList<String>();
                }
                return this.srcUrl;
            }

            /**
             * Gets the value of the srcOcr property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getSrcOcr() {
                return srcOcr;
            }

            /**
             * Sets the value of the srcOcr property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setSrcOcr(TextFieldType value) {
                this.srcOcr = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the version property.
             * 
             */
            public float getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             */
            public void setVersion(float value) {
                this.version = value;
            }

            /**
             * Gets the value of the history property.
             * 
             * @return
             *     possible object is
             *     {@link AnnotationType }
             *     
             */
            public AnnotationType getHistory() {
                return history;
            }

            /**
             * Sets the value of the history property.
             * 
             * @param value
             *     allowed object is
             *     {@link AnnotationType }
             *     
             */
            public void setHistory(AnnotationType value) {
                this.history = value;
            }

            /**
             * Gets the value of the publisher property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the publisher property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPublisher().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AuthorType }
             * 
             * 
             */
            public List<AuthorType> getPublisher() {
                if (publisher == null) {
                    publisher = new ArrayList<AuthorType>();
                }
                return this.publisher;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="book-name" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
         *         &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
         *         &lt;element name="city" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
         *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/&gt;
         *         &lt;element name="isbn" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/&gt;
         *         &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bookName",
            "publisher",
            "city",
            "year",
            "isbn",
            "sequence"
        })
        public static class PublishInfo {

            @XmlElement(name = "book-name")
            protected TextFieldType bookName;
            protected TextFieldType publisher;
            protected TextFieldType city;
            @XmlSchemaType(name = "gYear")
            protected XMLGregorianCalendar year;
            protected TextFieldType isbn;
            protected List<SequenceType> sequence;

            /**
             * Gets the value of the bookName property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getBookName() {
                return bookName;
            }

            /**
             * Sets the value of the bookName property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setBookName(TextFieldType value) {
                this.bookName = value;
            }

            /**
             * Gets the value of the publisher property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getPublisher() {
                return publisher;
            }

            /**
             * Sets the value of the publisher property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setPublisher(TextFieldType value) {
                this.publisher = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setCity(TextFieldType value) {
                this.city = value;
            }

            /**
             * Gets the value of the year property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setYear(XMLGregorianCalendar value) {
                this.year = value;
            }

            /**
             * Gets the value of the isbn property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getIsbn() {
                return isbn;
            }

            /**
             * Sets the value of the isbn property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setIsbn(TextFieldType value) {
                this.isbn = value;
            }

            /**
             * Gets the value of the sequence property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sequence property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSequence().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SequenceType }
             * 
             * 
             */
            public List<SequenceType> getSequence() {
                if (sequence == null) {
                    sequence = new ArrayList<SequenceType>();
                }
                return this.sequence;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Stylesheet {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
