//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 12:49:43 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gribuser.ru/xml/fictionbook/2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fb2;
