//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 12:49:43 AM EET 
//


package fb2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A poem
 * 
 * <p>Java class for poemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="poemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}titleType" minOccurs="0"/&gt;
 *         &lt;element name="epigraph" type="{http://www.gribuser.ru/xml/fictionbook/2.0}epigraphType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element name="subtitle" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType"/&gt;
 *           &lt;element name="stanza"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}titleType" minOccurs="0"/&gt;
 *                     &lt;element name="subtitle" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" minOccurs="0"/&gt;
 *                     &lt;element name="v" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" maxOccurs="unbounded"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="text-author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "poemType", propOrder = {
    "title",
    "epigraph",
    "subtitleOrStanza",
    "textAuthor",
    "date"
})
public class PoemType {

    protected TitleType title;
    protected List<EpigraphType> epigraph;
    @XmlElements({
        @XmlElement(name = "subtitle", type = PType.class),
        @XmlElement(name = "stanza", type = PoemType.Stanza.class)
    })
    protected List<Object> subtitleOrStanza;
    @XmlElement(name = "text-author")
    protected List<PType> textAuthor;
    protected DateType date;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link TitleType }
     *     
     */
    public TitleType getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleType }
     *     
     */
    public void setTitle(TitleType value) {
        this.title = value;
    }

    /**
     * Gets the value of the epigraph property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epigraph property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEpigraph().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EpigraphType }
     * 
     * 
     */
    public List<EpigraphType> getEpigraph() {
        if (epigraph == null) {
            epigraph = new ArrayList<EpigraphType>();
        }
        return this.epigraph;
    }

    /**
     * Gets the value of the subtitleOrStanza property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subtitleOrStanza property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubtitleOrStanza().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PType }
     * {@link PoemType.Stanza }
     * 
     * 
     */
    public List<Object> getSubtitleOrStanza() {
        if (subtitleOrStanza == null) {
            subtitleOrStanza = new ArrayList<Object>();
        }
        return this.subtitleOrStanza;
    }

    /**
     * Gets the value of the textAuthor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textAuthor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PType }
     * 
     * 
     */
    public List<PType> getTextAuthor() {
        if (textAuthor == null) {
            textAuthor = new ArrayList<PType>();
        }
        return this.textAuthor;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setDate(DateType value) {
        this.date = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}titleType" minOccurs="0"/&gt;
     *         &lt;element name="subtitle" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" minOccurs="0"/&gt;
     *         &lt;element name="v" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "subtitle",
        "v"
    })
    public static class Stanza {

        protected TitleType title;
        protected PType subtitle;
        @XmlElement(required = true)
        protected List<PType> v;
        @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "language")
        protected String lang;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link TitleType }
         *     
         */
        public TitleType getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link TitleType }
         *     
         */
        public void setTitle(TitleType value) {
            this.title = value;
        }

        /**
         * Gets the value of the subtitle property.
         * 
         * @return
         *     possible object is
         *     {@link PType }
         *     
         */
        public PType getSubtitle() {
            return subtitle;
        }

        /**
         * Sets the value of the subtitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link PType }
         *     
         */
        public void setSubtitle(PType value) {
            this.subtitle = value;
        }

        /**
         * Gets the value of the v property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the v property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getV().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PType }
         * 
         * 
         */
        public List<PType> getV() {
            if (v == null) {
                v = new ArrayList<PType>();
            }
            return this.v;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

    }

}
